import type { Metadata } from "next";

import "./globals.css";

import { Container } from "@/app/_layout/Container";
import { Header } from "./_layout/Header";
import { Main } from "./_layout/Main";
import { Footer } from "./_layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Container>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
